Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "manager01" do |manager|
    manager.vm.box = "ubuntu/jammy64"
    manager.vm.network "private_network", type: "dhcp"
    manager.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    manager.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y docker.io curl
      sudo systemctl restart ssh

      sudo usermod -aG docker vagrant

      sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose

      if ! docker info | grep -q "Swarm: active"; then
        docker swarm init --advertise-addr $(hostname -I | awk '{print $2}')
      else
        echo "Docker Swarm already initialized."
      fi

      SWARM_TOKEN=$(docker swarm join-token worker -q)
      MANAGER_IP=$(hostname -I | awk '{print $2}')

      echo $SWARM_TOKEN > /vagrant/swarm_token
      echo $MANAGER_IP > /vagrant/manager_ip

      if ! docker config ls | grep -q "nginx_config"; then
        docker config create nginx_config /home/vagrant/src/services/nginx/nginx.conf || { echo "Failed to create nginx_config"; exit 1; }
      else
        echo "Docker config nginx_config already exists."
      fi

      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      cd /home/vagrant/src
      services=("session-service" "hotel-service" "payment-service" "loyalty-service" "report-service" "booking-service" "gateway-service" "nginx")
      for service in "${services[@]}"; do
        cd "./services/$service"
        chmod +x mvnw
        docker build -t "digglega/$service:latest" .
        docker push "digglega/$service:latest"
        cd ../..
      done

      docker network create --driver overlay my_stack_network

      docker stack deploy -c /home/vagrant/src/docker-compose.yml my_stack

      docker volume create portainer_data
      docker stack deploy -c /home/vagrant/src/portainer-compose.yml portainer_stack

      if ! command -v newman &> /dev/null; then
        sudo apt-get update
        sudo apt-get install -y npm
        sudo npm install -g newman
      fi

      if [ -f /home/vagrant/src/application_tests.postman_collection.json ]; then
        newman run /home/vagrant/src/application_tests.postman_collection.json -r cli,html --reporter-html-export /home/vagrant/src/newman_report.html
      else
        echo "Postman collection application_tests.postman_collection.json not found."
      fi

      docker node ls
      docker stack ps my_stack
    SHELL

    manager.vm.synced_folder "/home/digglega/Documents/s21_projects/DevOps_7-1/src", "/home/vagrant/src", type: "rsync"
  end

  config.vm.define "worker01" do |worker|
    worker.vm.box = "ubuntu/jammy64"
    worker.vm.network "private_network", type: "dhcp"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    worker.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y docker.io curl
      sudo systemctl restart ssh

      sudo usermod -aG docker vagrant

      sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose

      while [ ! -f /vagrant/swarm_token ]; do
        sleep 1
      done
      SWARM_TOKEN=$(cat /vagrant/swarm_token)
      MANAGER_IP=$(cat /vagrant/manager_ip)

      if docker info | grep -q "Swarm: active"; then
        docker swarm leave --force
      fi

      for i in {1..5}; do
        docker swarm join --token $SWARM_TOKEN $MANAGER_IP:2377 && break || {
          echo "Failed to join Swarm, retrying in 15 seconds..."
          sleep 15
        }
      done
    SHELL
  end

  config.vm.define "worker02" do |worker|
    worker.vm.box = "ubuntu/jammy64"
    worker.vm.network "private_network", type: "dhcp"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    worker.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y docker.io curl
      sudo systemctl restart ssh

      sudo usermod -aG docker vagrant

      sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose

      while [ ! -f /vagrant/swarm_token ]; do
        sleep 1
      done
      SWARM_TOKEN=$(cat /vagrant/swarm_token)
      MANAGER_IP=$(cat /vagrant/manager_ip)

      if docker info | grep -q "Swarm: active"; then
        docker swarm leave --force
      fi

      for i in {1..5}; do
        docker swarm join --token $SWARM_TOKEN $MANAGER_IP:2377 && break || {
          echo "Failed to join Swarm, retrying in 15 seconds..."
          sleep 15
        }
      done
    SHELL
  end
end
